version: "3.8"

services:
  my-next-mui-large:
    build:
      context: .
      dockerfile: Dockerfile
    # image: my-next-mui-large-stg:${version}
    container_name: my-next-mui-large-stg
    ports:
      - "5001:5001"
    environment:
      - .env.${ENV}

  nginx:
    image: nginx:alpine
    container_name: nginx-stg
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - my-next-mui-large
# networks:
#   my_custom_network:
#     driver: bridge

# run command
# version=latest docker-compose up -d --build
